import { v4 as uuid } from "uuid";
import { product1 } from "../../assets";
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Chess Base 16",
    categoryName: "Book",
    price: "₹249",
    initialPrice: "₹449",
    discountPrice: "44% off",
    image: product1,
    alt: "p1",
  },
  {
    _id: uuid(),
    title: "Chess Kit",
    categoryName: "Pieces",
    price: "₹499",
    initialPrice: "₹699",
    discountPrice: "44% off",
    image: product1,
    alt: "p2",
  },
  {
    _id: uuid(),
    title: "Chess Board",
    categoryName: "Board",
    price: "₹849",
    initialPrice: "₹949",
    discountPrice: "44% off",
    image: product1,
    alt: "p3",
  },
  {
    _id: uuid(),
    title: "Chess Base 16",
    categoryName: "Book",
    price: "₹249",
    initialPrice: "₹449",
    discountPrice: "44% off",
    image: product1,
    alt: "p4",
  },
  {
    _id: uuid(),
    title: "Chess Base 16",
    categoryName: "Book",
    price: "₹249",
    initialPrice: "₹449",
    discountPrice: "44% off",
    image: product1,
    alt: "p5",
  },
  {
    _id: uuid(),
    title: "Chess Kit",
    categoryName: "Pieces",
    price: "₹499",
    initialPrice: "₹699",
    discountPrice: "44% off",
    image: product1,
    alt: "p6",
  },
  {
    _id: uuid(),
    title: "Chess Board",
    categoryName: "Board",
    price: "₹849",
    initialPrice: "₹949",
    discountPrice: "44% off",
    image: product1,
    alt: "p7",
  },
  {
    _id: uuid(),
    title: "Chess Base 16",
    categoryName: "Book",
    price: "₹249",
    initialPrice: "₹449",
    discountPrice: "44% off",
    image: product1,
    alt: "p8",
  },
  {
    _id: uuid(),
    title: "Chess Base 16",
    categoryName: "Book",
    price: "₹249",
    initialPrice: "₹449",
    discountPrice: "44% off",
    image: product1,
    alt: "p9",
  },
];
