export { awesomeIcons, productCategories } from "./constants";
export { filterReducer } from "./filter-reducer";
export { setRange } from "./setRange";
export { setRating } from "./setRating";
export { setAscSort } from "./setAscSort";
export { setDescSort } from "./setDescSort";
export { setAddCategory } from "./setAddCategory";
export { setRemoveCategory } from "./setRemoveCategory";
export { searchProduct } from "./searchProduct";
export { getProduct } from "./getProduct";
